name: Update Gold Price

on:
  schedule:
    - cron: '0 */1 * * 1-7'
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-gold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 gspread oauth2client

      - name: Run update gold price script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python giavang.py
